name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  
  info_data:
    runs-on: ubuntu-20.04
    steps:
      - name: Show date
        run: date

      - name: Show list
        run: ls